// Native 1080p real-time recording. QA access reads normal game state only.
const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/37818/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const ROOT=__dirname,WEB=path.resolve(ROOT,'../../../../../public'),OUT=path.join(ROOT,'capture',process.env.TAKE||'journey-01');fs.mkdirSync(OUT,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const server=http.createServer((req,res)=>{const file=path.resolve(WEB,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(WEB+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(data);});}).listen(0,'127.0.0.1');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=d3d11','--disable-background-timer-throttling','--disable-renderer-backgrounding','--autoplay-policy=no-user-gesture-required']});const context=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1}),p=await context.newPage(),errors=[],events=[],states=[],frames=[];let started=Date.now(),recording=false,lastSaved=0;
const held=new Set();async function keys(wanted){for(const k of [...held])if(!wanted.includes(k)){await p.keyboard.up(k);held.delete(k);}for(const k of wanted)if(!held.has(k)){await p.keyboard.down(k);held.add(k);}}
const mark=async(name)=>{const s=await observe();const e={name,t:(Date.now()-started)/1000,game:s.elapsed,state:s};events.push(e);console.log('EVENT',name,e.t.toFixed(2),JSON.stringify({...s,enemies:s.enemies.length}));await p.screenshot({path:path.join(OUT,name+'.png')});};
async function observe(){return p.evaluate(()=>{const q=__gameQA,s=q.rvBreakout.state,v=s.rv;return {active:s.active,over:s.over,state:q.Game.state,testMode:q.Game.testMode,elapsed:s.elapsed,x:v?.mesh.position.x,z:v?.mesh.position.z,px:q.player.pos.x,pz:q.player.pos.z,hp:v?.hp,max:v?.maxHp,person:q.player.hp,personMax:q.player.maxHp,dead:q.player.dead,inVehicle:!!q.player.inVehicle,yaw:q.getCamYaw(),cam:q.getCamMode(),scrap:s.scrap,fuel:s.fuel,gun:s.gun,looted:s.looted,defeated:s.defeated.length,food:s.food,medkits:q.Game.items.medkit,search:s.search,job:s.job,site:q.rvBreakout.atSite()?.id,interaction:q.interactionTarget()?.kind,enemies:q.monsters.filter(m=>m.rvZombie&&!m.dead).map(m=>({x:m.mesh.position.x,z:m.mesh.position.z,hp:m.hp,mode:m.mode})),result:document.getElementById('rvResultInfo').innerText};});}
async function route(goal){return p.evaluate(({goal})=>{const q=__gameQA,b=q.rvBreakout,r=b.state,from=q.player.inVehicle?r.rv.mesh.position:q.player.pos,radius=q.player.inVehicle?2.7:.85,step=4,x0=-172,z0=1504,W=87,H=91;
 const ix=x=>Math.max(0,Math.min(W-1,Math.round((x-x0)/step))),iz=z=>Math.max(0,Math.min(H-1,Math.round((z-z0)/step))),start=iz(from.z)*W+ix(from.x),end=iz(goal.z)*W+ix(goal.x),dist=new Float64Array(W*H).fill(Infinity),parent=new Int32Array(W*H).fill(-1),closed=new Uint8Array(W*H),open=[start];dist[start]=0;
 const h=k=>Math.abs(k%W-end%W)+Math.abs(Math.floor(k/W)-Math.floor(end/W));let found=false;
 while(open.length){open.sort((a,b)=>dist[b]+h(b)-dist[a]-h(a));const k=open.pop();if(closed[k])continue;closed[k]=1;if(k===end){found=true;break;}const x=k%W,z=Math.floor(k/W);for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,zz=z+dz;if(xx<0||xx>=W||zz<0||zz>=H)continue;const j=zz*W+xx;if(closed[j]||b.blocked(x0+xx*step,z0+zz*step,radius))continue;const d=dist[k]+1;if(d<dist[j]){dist[j]=d;parent[j]=k;open.push(j);}}}
 if(!found)throw Error('No ordinary route to '+JSON.stringify(goal));const a=[];for(let k=end;k!==start&&k>=0;k=parent[k])a.push({x:x0+k%W*step,z:z0+Math.floor(k/W)*step});a.reverse();const slim=[];for(let i=0;i<a.length;i++){const prev=a[i-1],next=a[i+1];if(!prev||!next||prev.x!==next.x&&prev.z!==next.z)slim.push(a[i]);}slim.push(goal);return slim;
 },{goal});}
async function navigate(goal,label){await keys([]);let waypoints=await route(goal),index=0,lastMove=Date.now(),last=null;const limit=Date.now()+90000;while(Date.now()<limit){const s=await observe();states.push({t:(Date.now()-started)/1000,...s,enemies:s.enemies.length});if(s.over||s.dead)throw Error('Normal journey ended during '+label);const pos=s.inVehicle?{x:s.x,z:s.z}:{x:s.px,z:s.pz};let target=waypoints[index];if(Math.hypot(goal.x-pos.x,goal.z-pos.z)<(s.inVehicle?3.3:1.6)){await keys([]);await mark(label);return;}
 if(Math.hypot(target.x-pos.x,target.z-pos.z)<(s.inVehicle?3.4:1.8)&&index<waypoints.length-1)target=waypoints[++index];
 const dx=target.x-pos.x,dz=target.z-pos.z,f=dx*Math.sin(s.yaw)+dz*Math.cos(s.yaw),r=-dx*Math.cos(s.yaw)+dz*Math.sin(s.yaw),want=[];if(Math.abs(f)>1)want.push(f>0?'KeyW':'KeyS');if(Math.abs(r)>1)want.push(r>0?'KeyD':'KeyA');
 if(s.enemies.some(e=>e.mode==='chase'&&Math.hypot(e.x-pos.x,e.z-pos.z)<35))want.push('KeyJ');await keys(want);
 if(last&&Math.hypot(last.x-pos.x,last.z-pos.z)>.8)lastMove=Date.now();if(Date.now()-lastMove>4500){await keys([]);waypoints=await route(goal);index=0;lastMove=Date.now();console.log('Replanned normal input route',label);}last=pos;
 if(s.person<s.personMax*.3&&!s.inVehicle&&s.medkits>0)await p.keyboard.press('KeyH');await sleep(220);
 }throw Error('Route timeout '+label);}
async function service(id,label,wait=0){await p.keyboard.press('KeyO');await sleep(700);await p.locator('#'+id).click();await sleep(wait||1000);if(await p.locator('#rvPanel').isVisible())await p.locator('#rvClose').click();await mark(label);}
async function defend(seconds){const end=Date.now()+seconds*1000;while(Date.now()<end){const s=await observe(),x=s.inVehicle?s.x:s.px,z=s.inVehicle?s.z:s.pz;await keys(s.enemies.some(e=>e.mode==='chase'&&Math.hypot(e.x-x,e.z-z)<35)?['KeyJ']:[]);await sleep(250);}await keys([]);}
async function search(goal,name){await navigate({x:goal.x-11,z:goal.z+2},name+'-arrive');await defend(5);await p.keyboard.press('KeyI');await sleep(500);await navigate(goal,name+'-on-foot');await p.keyboard.press('KeyI');await defend(5.2);const s=await observe();if(!s.looted.some(Boolean)||s.search)throw Error('Search did not finish');await mark(name+'-searched');await sleep(1500);await navigate({x:s.x,z:s.z},name+'-return-to-rv');await p.keyboard.press('KeyI');await sleep(500);if(!(await observe()).inVehicle)throw Error('Failed to board through normal interaction');await mark(name+'-boarded');}
try{p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{const connect=AudioNode.prototype.connect;AudioNode.prototype.connect=function(dest,...args){if(dest instanceof AudioDestinationNode){if(!this.context.__movieDest)this.context.__movieDest=this.context.createMediaStreamDestination();window.__movieAudio=this.context.__movieDest;return connect.call(this,this.context.__movieDest,...args);}return connect.call(this,dest,...args);};});
await p.goto('http://127.0.0.1:'+server.address().port+'/html/game/starship-defense/index.html?qa=1');await p.waitForFunction(()=>window.__ccReady&&window.__gameQA);await p.click('#keysMenu');await p.selectOption('#combat-input','keyboard');await p.selectOption('#combat-aim','auto');await p.selectOption('#combat-fire','hold');await p.click('#keysClose');await p.click('#btnRV');await p.screenshot({path:path.join(OUT,'mode-menu.png')});await p.click('#rvStart');await sleep(1500);if((await observe()).testMode)throw Error('Not normal rules');await p.keyboard.press('KeyC');
started=Date.now();await p.evaluate(()=>{window.__movieChunks=[];window.__movieRec=new MediaRecorder(__movieAudio.stream,{mimeType:'audio/webm;codecs=opus',audioBitsPerSecond:192000});__movieRec.ondataavailable=e=>__movieChunks.push(e.data);__movieRec.start(500);window.__movieAudioStart=Date.now();});const cdp=await context.newCDPSession(p);cdp.on('Page.screencastFrame',async e=>{if(recording&&e.metadata.timestamp-lastSaved>=.035){lastSaved=e.metadata.timestamp;const file=String(frames.length).padStart(6,'0')+'.jpg';fs.writeFileSync(path.join(OUT,file),Buffer.from(e.data,'base64'));frames.push({file,timestamp:e.metadata.timestamp});}await cdp.send('Page.screencastFrameAck',{sessionId:e.sessionId}).catch(()=>{});});recording=true;await cdp.send('Page.startScreencast',{format:'jpeg',quality:98,maxWidth:1920,maxHeight:1080,everyNthFrame:1});
await mark('start');await sleep(3500);await navigate({x:112,z:1545},'garage-arrive');await service('rvGun','gun-upgraded',6500);await navigate({x:-112,z:1565},'fuel-arrive');await service('rvFuel','fuel-filled',4500);await search({x:-55,z:1585},'homes');await navigate({x:-112,z:1700},'market-arrive');await service('rvFood','food-bought');if((await observe()).person<(await observe()).personMax)await service('rvEat','food-healed');await search({x:0,z:1688},'square');await navigate({x:112,z:1805},'repair-arrive');if((await observe()).hp<(await observe()).max-30)await service('rvRepair','vehicle-repaired',7500);await navigate({x:0,z:1848},'exit-arrive');await service('rvEvacuate','evacuated');await sleep(7000);await mark('final-result');await cdp.send('Page.stopScreencast');recording=false;
const audio=await p.evaluate(async()=>{await new Promise(r=>{__movieRec.onstop=r;__movieRec.stop();});return {start:__movieAudioStart,bytes:Array.from(new Uint8Array(await new Blob(__movieChunks).arrayBuffer()))};});fs.writeFileSync(path.join(OUT,'game-audio.webm'),Buffer.from(audio.bytes));const data={started,audioStart:audio.start,duration:(Date.now()-started)/1000,frames,events,states,errors,finalState:await observe(),gameplay_modified:false,time_scale:1,normal_rule_inputs_only:true};fs.writeFileSync(path.join(OUT,'capture.json'),JSON.stringify(data,null,2));console.log('CAPTURE COMPLETE',data.duration,frames.length);
}catch(e){fs.writeFileSync(path.join(OUT,'failure.json'),JSON.stringify({error:e.stack,events,frames:frames.length,errors},null,2));throw e;}finally{await keys([]).catch(()=>{});recording=false;await context.close();await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
