import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url)),kit=path.join(root,'media-kit'),release='releases/v0.1.0',cap=path.join(kit,release,'captures');
const build=JSON.parse(fs.readFileSync(path.resolve(root,'../../public/html/game/jackal-3d/build.json'),'utf8'));
const write=(file,data)=>fs.writeFileSync(path.join(kit,file),JSON.stringify(data,null,2)+'\n');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const ffmpeg=process.env.FFMPEG||'D:/project/toolbasecamp/comfyui-api-server/.venv/Lib/site-packages/imageio_ffmpeg/binaries/ffmpeg-win64-v4.2.2.exe';
const buildId='jackal-v0.1.0-'+build.fingerprint.slice(0,12),media=[];
for(const file of fs.readdirSync(cap)){if(!/\.(png|webm|mp4)$/.test(file))continue;const p=path.join(cap,file),audio=file==='playthrough-audio.webm',video=/\.(webm|mp4)$/.test(file)&&!audio;let width=null,height=null,duration=null;
 if(file.endsWith('.png')){const b=fs.readFileSync(p);width=b.readUInt32BE(16);height=b.readUInt32BE(20);}else{const r=spawnSync(ffmpeg,['-hide_banner','-i',p],{encoding:'utf8'}),s=r.stderr;const d=s.match(/Duration: (\d+):(\d+):([\d.]+)/);if(!d)throw Error('Cannot probe '+file);duration=+d[1]*3600+(+d[2])*60+(+d[3]);const size=s.match(/Video:.*? (\d{3,5})x(\d{3,5})/);if(size){width=+size[1];height=+size[2];}}
 const id=file.replace(/\.[^.]+$/,'');let description=id;if(file.startsWith('phone-'))description='桌面 Edge 手机视口模拟：'+id+'；CDP 多点触摸，非物理手机';if(file==='playthrough.webm')description='完整第一关正常键盘输入实机：9 人撤离、四辆坦克、结算；无作弊';if(file==='playthrough-audio.webm')description='同一次通关的独立游戏音轨；相对画面开始约后移 0.65 秒，尚需逐事件校准';if(file.startsWith('performance'))description='性能测试定点营区，含明确测试保护与传送';
 media.push({id,file:release+'/captures/'+file,sha256:sha(p),kind:audio?'audio':video?'video':'screenshot',version:'v0.1.0',build_id:buildId,capture_mode:'realtime-automation',description,width,height,duration_seconds:duration,audio:audio||file.endsWith('.mp4')?'game':'none',visual_review:audio?'not-applicable':video?'not-run':'pass',audio_review:audio||file.endsWith('.mp4')?'not-run':'not-applicable',segments:video?[{in_seconds:0,out_seconds:Math.min(duration,75),description}]:[]});
}
const feats=[['drive','吉普驾驶、机枪、榴弹与导弹升级',['officer-upgrade','first-rescue']],['rescue','四座营房、九人救援、直升机撤离',['prison-camp','helicopter-evacuation','result']],['boss','四波重型坦克与预警弹幕',['tank-wave-1','tank-wave-3','tank-wave-4','result']],['controls','键盘、横屏触屏、竖屏自动旋转和单按钮视角',['phone-844-multitouch','phone-390-multitouch']],['loop','检查点无限复活、结算、重玩与独立最高分',['result']]].map(([id,description,evidence_ids])=>({id,description,status:'implemented',evidence_ids}));
const qa=[];for(const f of ['functional.json','performance.json','playthrough.json','local-site.json','online-site.json']){const p=path.join(cap,f);if(fs.existsSync(p))qa.push({id:f.replace('.json',''),evidence:release+'/captures/'+f,...JSON.parse(fs.readFileSync(p,'utf8'))});}
write('game.json',{game_id:'jackal-3d',name:'赤色要塞 · 前线营救 3D',engine:'Three.js r152',current_version:'v0.1.0',handoff:release+'/handoff.json',entrypoint:'public/html/game/jackal-3d/index.html',source:'game-projects/jackal-3d/src',build_command:'node game-projects/jackal-3d/build.mjs',local_url:'http://127.0.0.1:8876/html/game/jackal-3d/index.html',website_url:'https://www.zhengxiaohui.cn/html/game/jackal-3d/index.html',website_verified:fs.existsSync(path.join(cap,'online-site.json')),release_intent:'web_demo',development_model:null,tools:['Codex','Three.js','Playwright','Web Audio','FFmpeg'],controls:'WASD/J/K/L/C，Enter，Esc，M；手机左摇杆和右动作按钮',toy:{id:null,slug:null,url:null,visibility:null,review_status:'not_submitted',verified_at:null,video_bindings:[]}});
write('sources.json',[
 {id:'models',purpose:'吉普、人物、坦克、炮台、建筑、直升机、植被与残骸',source_type:'procedural',original_file:'../src/art.js',runtime_file:'public/html/game/jackal-3d/art.js',tool:'Three.js primitives and merged vertex-colored geometry',model:null,parameters:'src/art.js，固定地图随机种子 91422',processing:'共享几何、材质与分块合批；原创参数化建模',usage_conditions:'项目原创程序化资源，无外部模型或 ROM 提取',placeholder:false},
 {id:'sound',purpose:'射击、爆炸、营救、升级、胜利与背景节拍',source_type:'procedural',original_file:'../src/audio.js',runtime_file:'public/html/game/jackal-3d/audio.js',tool:'Web Audio API',processing:'振荡器与噪声合成，绑定游戏事件',usage_conditions:'原创合成音色与短节拍；未提取原游戏声音',placeholder:false},
 {id:'three',purpose:'3D 引擎',source_type:'licensed',original_file:'../src/vendor/three.module.js',runtime_file:'public/html/game/jackal-3d/vendor/three.module.js',tool:'Three.js r152',usage_conditions:'MIT，许可证随运行文件提供'},
 {id:'rules-reference',purpose:'核对原版营救和第一关坦克流程',source_type:'reference',urls:['https://www.world-of-nintendo.com/manuals/nes/jackal.shtml','https://gamefaqs.gamespot.com/nes/563425-jackal/faqs/20059'],processing:'规则参考与原创三维改编，不是贴图或音频来源'},
 {id:'catalog-thumb',purpose:'游戏列表封面',source_type:'procedural',original_file:release+'/captures/helicopter-evacuation.png',runtime_file:'public/assets/game/thumbs/jackal-3d.jpg',tool:'Playwright capture + sharp resize',processing:'真实实机截图缩放至 640×360 JPEG',usage_conditions:'本项目当前游戏截图'}
]);
write(release+'/handoff.json',{schema_version:1,game_id:'jackal-3d',version:'v0.1.0',base_version:null,created_at:new Date().toISOString(),build:{id:buildId,commit:null,dirty:true,fingerprint:build.fingerprint,entrypoint:'public/html/game/jackal-3d/index.html'},feature_inventory:feats,changes:[{id:'first-level',feature_ids:feats.map(f=>f.id),before:'新建项目',after:'可完整通关的第一关 3D Demo',visible_result:'吉普突破、战俘救援与四辆坦克决战',evidence_ids:['result','playthrough'],verification:'passed'}],bugs:[{id:'mixed-geometry',status:'fixed',observed:'混合索引和非索引几何导致合批失败',fix:'统一为非索引几何',before_media_ids:[],after_media_ids:['first-play'],retest:'浏览器正常载入',gap:'未录故障原片'},{id:'negative-respawn',status:'fixed',observed:'复活倒计时负数被真值判断当成仍在死亡',fix:'复活显式将 dead 归零',before_media_ids:[],after_media_ids:[],retest:'functional.json：三次击毁复活、保护到期后扣血',gap:'只有诊断状态记录，没有故障原片'},{id:'camera-held-input',status:'fixed',observed:'切视角清空正在按住的触控状态',fix:'相同水平轴视角切换保留按住状态',before_media_ids:[],after_media_ids:['phone-390-multitouch'],retest:'移动与射击保持期间切换两次视角'}],media,historical_media:[],qa,readiness:{overview:'partial',update:'not_applicable',gaps:['原始录像与单独游戏音轨已留存，但逐事件同步和主观听审待完成。','连续帧已检查；整段逐秒视频审查未完成。','手机为视口和触摸模拟，未测试物理手机。','未提供 ffprobe；实际媒体参数由 FFmpeg 输入探测读取。']}});
console.log(JSON.stringify({buildId,media:media.length,qa:qa.length}));
