// Realtime browser capture. Gameplay is controlled only with normal UI and keyboard input.
const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/37818/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/project/toolbasecamp/game-projects/starship-defense/video/update-20261003/work';
async function open(){
 const server=http.createServer((req,res)=>{const p=path.join(root,'build-current',decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(path.join(root,'build-current')))return res.end();fs.readFile(p,(e,d)=>{if(e){res.statusCode=404;return res.end();}res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.html')?'text/html':p.endsWith('.css')?'text/css':'application/octet-stream');res.end(d);});}).listen(8879,'127.0.0.1');
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--use-angle=d3d11','--disable-background-timer-throttling','--disable-renderer-backgrounding','--autoplay-policy=no-user-gesture-required']});
 const context=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1});const p=await context.newPage();
 await p.addInitScript(()=>{const connect=AudioNode.prototype.connect;AudioNode.prototype.connect=function(dest,...args){if(dest instanceof AudioDestinationNode){window.__captureAudio=this.context.createMediaStreamDestination();window.__captureAudioContext=this.context;return connect.call(this,window.__captureAudio,...args);}return connect.call(this,dest,...args);};});
 const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8879/index.html?qa=1');await p.waitForFunction(()=>window.__gameQA);
 const cdp=await context.newCDPSession(p);let recording=null;
 cdp.on('Page.screencastFrame',async e=>{const r=recording;if(r){const n=r.frames.length;fs.writeFileSync(path.join(r.dir,`${String(n).padStart(6,'0')}.jpg`),Buffer.from(e.data,'base64'));r.frames.push({file:`${String(n).padStart(6,'0')}.jpg`,timestamp:e.metadata.timestamp});}await cdp.send('Page.screencastFrameAck',{sessionId:e.sessionId}).catch(()=>{});});
 const state=()=>p.evaluate(()=>{const q=__gameQA;return {state:q.Game.state,level:q.Game.level,gold:q.Game.gold,score:q.Game.score,hp:q.player.hp,maxHp:q.player.maxHp,pos:q.player.pos.toArray(),base:q.base.hp,yaw:q.getCamYaw(),mode:q.getCamMode(),weapons:q.Game.weapons,weapon:q.Game.curWeapon,test:q.Game.testMode,panel:q.panelOpen,op:q.operations?.active?.cfg?.name,monsters:q.monsters.filter(m=>!m.dead).map(m=>({x:m.mesh.position.x,z:m.mesh.position.z,hp:m.hp,kind:m.kind,wild:m.wild})),squad:q.squad.map(s=>({pos:s.mesh.position.toArray(),hp:s.hp})),vehicles:q.vehicles.map(v=>({kind:v.kind,pos:v.mesh.position.toArray()})),hive:q.Game.hive};});
 const held=new Set();
 const keys=async wanted=>{for(const k of [...held])if(!wanted.includes(k)){await p.keyboard.up(k);held.delete(k);}for(const k of wanted)if(!held.has(k)){await p.keyboard.down(k);held.add(k);}};
 async function start(name){if(recording)throw Error('already recording');const dir=path.join(root,'capture',name);fs.mkdirSync(dir,{recursive:true});recording={name,dir,frames:[],events:[],started:Date.now()};await p.evaluate(()=>{if(!window.__captureAudio)return;window.__captureChunks=[];window.__captureRec=new MediaRecorder(__captureAudio.stream,{mimeType:'audio/webm;codecs=opus',audioBitsPerSecond:192000});__captureRec.ondataavailable=e=>__captureChunks.push(e.data);__captureRec.start(200);window.__audioStart=Date.now();});await cdp.send('Page.startScreencast',{format:'jpeg',quality:95,maxWidth:1920,maxHeight:1080,everyNthFrame:2});return name;}
 async function stop(){await keys([]);await cdp.send('Page.stopScreencast');const r=recording;recording=null;const audio=await p.evaluate(async()=>{if(!window.__captureRec)return null;await new Promise(ok=>{__captureRec.onstop=ok;__captureRec.stop();});return {start:__audioStart,data:Array.from(new Uint8Array(await new Blob(__captureChunks).arrayBuffer()))};});if(audio){fs.writeFileSync(path.join(r.dir,'game-audio.webm'),Buffer.from(audio.data));r.audioStart=audio.start;}r.duration=(Date.now()-r.started)/1000;r.finalState=await state();r.errors=errors;r.capture_mode='realtime-automation';r.gameplay_modified=false;fs.writeFileSync(path.join(r.dir,'capture.json'),JSON.stringify(r,null,2));return {name:r.name,duration:r.duration,frames:r.frames.length,state:r.finalState};}
 async function move(x,z,seconds=20){const until=Date.now()+seconds*1000;while(Date.now()<until){const s=await state();if(s.panel||!['prep','battle'].includes(s.state))break;const dx=x-s.pos[0],dz=z-s.pos[2];if(Math.hypot(dx,dz)<2)break;const f=dx*Math.sin(s.yaw)+dz*Math.cos(s.yaw),r=-dx*Math.cos(s.yaw)+dz*Math.sin(s.yaw);let ks=[];if(Math.abs(f)>1.5)ks.push(f>0?'KeyW':'KeyS');if(Math.abs(r)>1.5)ks.push(r>0?'KeyD':'KeyA');await keys(ks);await p.waitForTimeout(160);}await keys([]);return state();}
 function mark(text){if(recording)recording.events.push({t:(Date.now()-recording.started)/1000,text});}
 return {server,browser,context,p,cdp,state,keys,start,stop,move,mark,errors,root};
};
open().then(cap=>{global.cap=cap;http.createServer(async(req,res)=>{let raw='';for await(const b of req)raw+=b;try{const code=JSON.parse(raw).code;const result=await new Function('cap','return (async()=>{'+code+'})()')(cap);res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result??{ok:true}));}catch(e){res.statusCode=500;res.end(JSON.stringify({error:e.stack}));}}).listen(8878,'127.0.0.1',()=>console.log('READY 8878'));}).catch(e=>{console.error(e);process.exit(1);});
