server {
    listen 80;
    listen [::]:80;
    server_name toolbasecamp.com www.toolbasecamp.com;

    root /var/www/toolbasecamp;
    index index.html;

    include snippets/toolbasecamp-static-cache.conf;
    include snippets/toolbasecamp-api.conf;

    location = /tools/pdf-to-word.html {
        return 301 /html/docs/pdf-to-word.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    gzip on;
    gzip_types text/css application/javascript text/html application/json;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name toolbasecamp.com www.toolbasecamp.com;

    ssl_certificate /etc/letsencrypt/live/toolbasecamp.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/toolbasecamp.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/toolbasecamp;
    index index.html;

    include snippets/toolbasecamp-static-cache.conf;
    include snippets/toolbasecamp-api.conf;

    location = /tools/pdf-to-word.html {
        return 301 /html/docs/pdf-to-word.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    gzip on;
    gzip_types text/css application/javascript text/html application/json;
}
