server {
    listen 80;
    listen [::]:80;
    server_name toolbasecamp.com www.toolbasecamp.com;
    return 301 https://zhengxiaohui.cn$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name toolbasecamp.com www.toolbasecamp.com;

    ssl_certificate /etc/letsencrypt/live/toolbasecamp.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/toolbasecamp.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://zhengxiaohui.cn$request_uri;
}
