server {
    listen 80;
    listen [::]:80;
    server_name chef.toolbasecamp.com;

    root /var/www/toolbasecamp-chef;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        gzip off;
        sub_filter '</head>' '<link rel="stylesheet" href="/portal-home-bar.css"><script src="/portal-home-bar.js"></script></head>';
        sub_filter_once on;
        sub_filter_types text/html;
    }

    gzip on;
    gzip_types text/css application/javascript application/json;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name chef.toolbasecamp.com;

    ssl_certificate /etc/letsencrypt/live/toolbasecamp.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/toolbasecamp.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/toolbasecamp-chef;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        gzip off;
        sub_filter '</head>' '<link rel="stylesheet" href="/portal-home-bar.css"><script src="/portal-home-bar.js"></script></head>';
        sub_filter_once on;
        sub_filter_types text/html;
    }

    gzip on;
    gzip_types text/css application/javascript application/json;
}
