const {chromium}=require('C:/Users/37818/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const url=process.env.GAME_URL||'http://127.0.0.1:8898/html/game/starship-defense/index.html';
const out=process.env.QA_OUTPUT||path.join(__dirname,'media-kit/releases/web-jump-v0.17.3');
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({channel:'msedge',headless:true});const results=[];
try{for(const mobile of [false,true]){
 const ctx=await b.newContext({viewport:mobile?{width:915,height:412}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile,...(process.env.RECORD==='1'&&!mobile?{recordVideo:{dir:out+'/video',size:{width:1280,height:720}}}:{})});
 const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);let f=p;
 if(process.env.TOY_PREVIEW==='1'){await p.locator('iframe').first().waitFor();f=await(await p.locator('iframe').first().elementHandle()).contentFrame();await f.waitForSelector('#btnStart');}
 await f.goto(f.url()+(f.url().includes('?')?'&':'?')+'qa=1');await f.waitForFunction(()=>window.__gameQA);await f.locator('#btnStart').click();
 const setup=()=>f.evaluate(()=>{const q=__gameQA;q.clearEntities(false);q.CombatControls.set('fire','hold');q.player.pos.set(0,q.groundY(0,40),40);q.player.mesh.position.copy(q.player.pos);q.player.vy=0;q.player.onGround=true;q.player.invulnerable=0;q.player.shield=0;q.player.hp=q.player.maxHp;q.Input.reset();});
 const jump=()=>mobile?f.locator('#vK').tap():p.keyboard.press('KeyK');
 await setup();await jump();await f.waitForTimeout(120);const up=await f.evaluate(()=>({y:__gameQA.player.pos.y-__gameQA.groundY(0,40),vy:__gameQA.player.vy,z:__gameQA.player.pos.z}));assert.ok(up.y>.4&&up.vy>0);assert.ok(Math.abs(up.z-40)<.05);
 await p.screenshot({path:out+(mobile?'/mobile-jump.jpg':'/desktop-jump.jpg')});await jump();await f.waitForTimeout(60);assert.ok(await f.evaluate(()=>__gameQA.player.vy)<up.vy,'airborne presses must not restart jump');
 const damage=await f.evaluate(()=>{const q=__gameQA,before=q.player.hp;q.playerDamage(10);return before-q.player.hp;});assert.ok(damage>0,'jump does not grant dash invulnerability');
 await f.waitForTimeout(850);assert.ok(await f.evaluate(()=>__gameQA.player.onGround));if(mobile)await jump();else await p.keyboard.press('Space');await f.waitForTimeout(100);assert.ok(await f.evaluate(()=>__gameQA.player.vy)>0,'jump again immediately after landing');await f.waitForTimeout(800);
 // Pause consumes no gameplay action; resume and first-person jump still work.
 await f.locator(mobile?'#vP':'#menuButton').click();await p.keyboard.press('KeyK');await f.waitForTimeout(100);assert.ok(await f.evaluate(()=>__gameQA.player.onGround));if(await f.locator('#btnResume').isVisible())await f.locator('#btnResume').click();await f.evaluate(()=>__gameQA.setCamMode('first',false));await jump();await f.waitForTimeout(100);assert.ok(await f.evaluate(()=>__gameQA.player.vy)>0);await f.waitForTimeout(800);await f.evaluate(()=>__gameQA.setCamMode('third',false));
 // Deterministic physics checks cover low roofs and walls without waiting for AI.
 const physics=await f.evaluate(()=>{const q=__gameQA;q.Game.state='paused';q.Input.reset();q.player.pos.set(0,q.groundY(0,240),240);q.player.vy=0;q.player.onGround=true;q.Input.pressed.K=true;const gy=q.groundY(0,240),limit=q.fortress.ceilingAt(0,240,gy+.1)-2.6;let peak=gy;for(let i=0;i<130;i++){q.updPlayer(1/120);peak=Math.max(peak,q.player.pos.y);}const cave={peak:peak-gy,landed:q.player.onGround,belowRoof:peak<=limit+.001};q.player.pos.set(0,q.groundY(0,40),40);q.player.vy=0;q.player.onGround=true;q.setCamYaw(0);q.placeBuilding('wall',0,44,0);q.Input.keys.up=true;q.Input.pressed.K=true;for(let i=0;i<120;i++)q.updPlayer(1/120);const wallZ=q.player.pos.z;q.Input.reset();q.damageBuilding(q.buildings[q.buildings.length-1],1e6);q.Game.state='prep';return{cave,wallZ};});assert.ok(physics.cave.peak>0&&physics.cave.landed&&physics.cave.belowRoof);assert.ok(physics.wallZ<44);
 await f.evaluate(()=>{const q=__gameQA;const v=q.spawnVehicle('heli');v.mesh.position.set(0,4,40);v.alt=4;q.enterVehicle(v);});await f.waitForTimeout(80);const alt0=await f.evaluate(()=>__gameQA.player.inVehicle.alt);if(mobile){const box=await f.locator('#vK').boundingBox();await p.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);}else{await p.keyboard.down('KeyK');await f.waitForTimeout(150);await p.keyboard.up('KeyK');}const alt1=await f.evaluate(()=>__gameQA.player.inVehicle.alt);assert.ok(alt1>=alt0);assert.equal(await f.locator('#vK').innerText(),'升');await f.evaluate(()=>__gameQA.exitVehicle());await f.waitForTimeout(200);assert.equal(await f.locator('#vK').innerText(),'跳跃');
 if(mobile){await p.setViewportSize({width:412,height:915});await f.waitForTimeout(200);await jump();await f.waitForTimeout(100);assert.ok(await f.evaluate(()=>__gameQA.player.vy)>0);await p.screenshot({path:out+'/portrait-jump.jpg'});}
 assert.deepEqual(errors,[]);results.push({mobile,up,damage,physics,errors});await ctx.close();
}fs.writeFileSync(out+'/qa.json',JSON.stringify({url,results},null,2));console.log(JSON.stringify(results));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
