// Original synthesized events and a quiet four-note mission pulse. No sampled game audio.
export class Sound {
 constructor(){this.ctx=null;this.muted=false;this.paused=true;this.step=0;this.next=0;}
 unlock(){if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=.24;this.master.connect(this.ctx.destination);this.capture=this.ctx.createMediaStreamDestination();this.master.connect(this.capture);}if(this.ctx.state==='suspended')this.ctx.resume();}
 mute(value){this.muted=value;if(this.master)this.master.gain.setTargetAtTime(value?0:.24,this.ctx.currentTime,.03);}
 tone(freq,duration=.1,type='square',volume=.1,end){if(!this.ctx||this.paused||this.muted)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+duration);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration);}
 noise(duration=.18,volume=.3){if(!this.ctx||this.paused||this.muted)return;const n=this.ctx.sampleRate*duration,b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),data=b.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*(1-i/n)**2;const src=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();src.buffer=b;f.type='lowpass';f.frequency.value=1700;g.gain.value=volume;src.connect(f);f.connect(g);g.connect(this.master);src.start();}
 play(name){if(name==='gun'){this.tone(125,.055,'sawtooth',.09,50);this.noise(.035,.13);}if(name==='heavy'){this.tone(250,.18,'sawtooth',.19,48);this.noise(.12,.2);}if(name==='boom'){this.noise(.38,.65);this.tone(88,.3,'sine',.45,28);}if(name==='hit'){this.tone(125,.2,'triangle',.35,50);this.noise(.12,.3);}if(name==='rescue'){this.tone(660,.16,'sine',.3);setTimeout(()=>this.tone(880,.2,'sine',.23),90);}if(name==='upgrade'){[440,660,880,1100].forEach((f,i)=>setTimeout(()=>this.tone(f,.22,'triangle',.3),i*100));}if(name==='win'){[523,659,784,1046].forEach((f,i)=>setTimeout(()=>this.tone(f,.45,'triangle',.4),i*180));}}
 update(time){if(time<this.next||this.paused)return;this.next=time+.28;const melody=[110,0,110,165,0,131,0,165,98,0,98,147,0,123,0,147];const f=melody[this.step++%melody.length];if(f)this.tone(f,.22,'triangle',.055);if(this.step%4===0)this.noise(.04,.02);}
}
