import {T,jeep,person,tank,cannon,hut,helicopter,sign,makeWorld,rubble,C} from './art.js';
import {Input} from './input.js';
import {Sound} from './audio.js';
const $=id=>document.getElementById(id),clamp=T.MathUtils.clamp,dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),angle=(x,z)=>Math.atan2(x,-z);
const sound=new Sound();
const renderer=new T.WebGLRenderer({canvas:$('scene'),antialias:true,alpha:false,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new T.Scene();scene.background=new T.Color(0x8eac9e);scene.fog=new T.Fog(0x8eac9e,65,110);
scene.add(new T.HemisphereLight(0xd4f2e7,0x687355,.9));const sun=new T.DirectionalLight(0xffe8b9,1.65);sun.position.set(-18,35,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-36;sun.shadow.camera.right=36;sun.shadow.camera.top=36;sun.shadow.camera.bottom=-36;sun.shadow.camera.near=1;sun.shadow.camera.far=100;sun.shadow.bias=-.00035;sun.shadow.normalBias=.055;scene.add(sun,sun.target);
const camera=new T.OrthographicCamera(-30,30,17,-17,.5,130),world=makeWorld(scene),dynamic=new T.Group();scene.add(dynamic);
const car=jeep();dynamic.add(car);const chopper=helicopter();scene.add(chopper);
const shield=new T.Mesh(new T.TorusGeometry(1.65,.045,5,48),new T.MeshBasicMaterial({color:0xaafce2}));shield.rotation.x=Math.PI/2;scene.add(shield);
const pointer=new T.Mesh(new T.ConeGeometry(.6,1.2,3),new T.MeshBasicMaterial({color:0xffdf85}));pointer.rotation.x=-Math.PI/2;scene.add(pointer);
const bulletGeo=new T.SphereGeometry(1,8,5),gold=new T.MeshBasicMaterial({color:0xffe69d}),red=new T.MeshBasicMaterial({color:0xff6041}),heavyMat=new T.MeshBasicMaterial({color:0xd9ffdf});
const wrecks=[],effects=[],shots=[],enemies=[],buildings=[],prisoners=[],hazards=[],sparks=[];
const sparkMesh=new T.InstancedMesh(new T.IcosahedronGeometry(1,0),new T.MeshBasicMaterial({vertexColors:false}),200);sparkMesh.instanceMatrix.setUsage(T.DynamicDrawUsage);sparkMesh.frustumCulled=false;scene.add(sparkMesh);const dummy=new T.Object3D();
const ringGeo=new T.RingGeometry(.86,1,36),ringMats={green:new T.MeshBasicMaterial({color:0x8eefd0,transparent:true,opacity:.65,side:T.DoubleSide}),red:new T.MeshBasicMaterial({color:0xff6349,transparent:true,opacity:.75,side:T.DoubleSide})};
const heliring=new T.Mesh(new T.RingGeometry(5.7,5.9,64),ringMats.green);heliring.rotation.x=-Math.PI/2;heliring.position.set(7,.2,-145);scene.add(heliring);
let mode='menu',view=0,time=0,elapsed=0,score=0,rescued=0,deaths=0,invincible=false,usedDemo=false,checkpoint={x:0,z:6},stage=0,bossSpawned=0,bossKilled=0,bossTimer=0,extract=0,extractCount=0,heliDepart=0,toastTime=0,hitShake=0,hudTimer=0,lastZone=-1,maxProgress=0;
const player={x:0,z:6,angle:0,hp:5,invuln:0,dead:0,cargo:[],level:0,gunCD:0,heavyCD:0,boost:0};
const touchDefault=matchMedia('(pointer:coarse)').matches;$('touch-toggle').checked=touchDefault;
const input=new Input(command);
function toast(message,seconds=3.5){$('toast').textContent=message;$('toast').classList.add('visible');toastTime=seconds;}
function place(obj,x,z,y=0){obj.position.set(x,y,z);dynamic.add(obj);return obj;}
function disposeTransient(obj){obj.removeFromParent();if(obj.userData.temporaryMaterial)obj.material.dispose();}
function addEnemy(type,x,z,boss=false){const root=type==='soldier'?person():type==='cannon'?cannon():tank(boss);place(root,x,z);const hp=type==='soldier'?3:type==='cannon'?18:boss?100:29;const e={type,x,z,hp,maxHp:hp,root,boss,r:type==='soldier'?.48:type==='cannon'?1.6:boss?2.0:1.5,cool:1.3+(enemies.length%4)*.33,aim:0,wind:0,flash:0,dead:false,phase:0};
 const hpMat=new T.MeshBasicMaterial({color:boss?0xff9363:0xefce89});const hpMesh=new T.Mesh(new T.PlaneGeometry(2,.12),hpMat);hpMesh.position.y=type==='soldier'?2.05:3.2;hpMesh.rotation.x=-Math.PI/3;root.add(hpMesh);e.hpMesh=hpMesh;
 const aimMesh=new T.Mesh(new T.PlaneGeometry(.1,19),new T.MeshBasicMaterial({color:0xff714e,transparent:true,opacity:.6,side:T.DoubleSide}));aimMesh.rotation.x=-Math.PI/2;aimMesh.visible=false;scene.add(aimMesh);e.aimMesh=aimMesh;enemies.push(e);return e;}
function addHut(x,z,officer,count){const root=hut(officer);place(root,x,z);const s=sign(officer?'★ 军官':'战俘 ×'+count,officer?'#ffd16f':'#bfefc9',4.5);s.position.set(0,4.3,0);s.rotation.x=-.45;root.add(s);buildings.push({x,z,r:3.1,w:5.4,d:4.8,hp:12,maxHp:12,root,officer,count,dead:false});}
function reset(){
 for(const e of enemies){e.root.removeFromParent();e.aimMesh.geometry.dispose();e.aimMesh.material.dispose();e.aimMesh.removeFromParent();e.hpMesh.material.dispose();e.hpMesh.geometry.dispose();}for(const b of buildings){const s=b.root.children.find(c=>c.material?.map);if(s){s.material.map.dispose();s.material.dispose();s.geometry.dispose();}b.root.removeFromParent();}for(const p of prisoners)p.root.removeFromParent();for(const s of shots)disposeTransient(s.mesh);for(const h of hazards){h.mesh.removeFromParent();h.mesh.material.dispose();}for(const e of effects)disposeTransient(e.mesh);
 for(const w of wrecks)w.removeFromParent();wrecks.length=0;enemies.length=buildings.length=prisoners.length=shots.length=hazards.length=effects.length=sparks.length=0;
 Object.assign(player,{x:0,z:6,angle:0,hp:5,invuln:2.8,dead:0,cargo:[],level:0,gunCD:0,heavyCD:0,boost:0});elapsed=score=rescued=deaths=stage=bossSpawned=bossKilled=bossTimer=extract=extractCount=heliDepart=lastZone=maxProgress=0;lastZone=-1;checkpoint={x:0,z:6};invincible=$('demo').checked;usedDemo=invincible;car.visible=true;chopper.visible=true;
 addHut(10,-16,true,1);addHut(-11,-44,false,3);addHut(-10,-110,false,4);addHut(11,-117,true,1);
 [['soldier',-4,-10],['soldier',5,-19],['cannon',-10,-25],['soldier',-3,-29],['tank',5,-37],['soldier',2,-48],['cannon',10,-54],['cannon',-15,-60],['soldier',-10,-87],['cannon',-4,-88],['tank',7,-103],['soldier',-3,-103],['soldier',3,-114],['cannon',-14,-123],['tank',-4,-133],['soldier',6,-130],['cannon',13,-163],['soldier',-3,-164]].forEach(([type,x,z])=>addEnemy(type,x,z));
 $('result').hidden=true;$('menu').hidden=true;$('pause-menu').hidden=true;$('hud').hidden=false;$('death').hidden=true;$('pause-demo').textContent='演示无敌：'+(invincible?'开':'关');mode='playing';sound.unlock();sound.paused=false;input.clear();resize();toast('前线已抵达。向前推进，炸开右侧 ★ 军官营房。',5);hud();
}
function command(c){if(c==='confirm'){if(mode==='menu'||mode==='win')reset();else if(mode==='paused')pause(false);}if(c==='pause'){if(mode==='playing')pause(true);else if(mode==='paused')pause(false);}if(c==='blur'&&mode==='playing')pause(true);if(c==='camera'&&mode==='playing'){view=(view+1)%2;$('camera-label').textContent=view?'正俯视':'斜俯视';toast(view?'切换为正俯视':'切换为斜俯视',1.3);}if(c==='mute')toggleMute();}
function pause(on){if(mode==='win'||mode==='menu')return;mode=on?'paused':'playing';$('pause-menu').hidden=!on;input.clear();sound.paused=on;if(on){$('resume').focus();if(sound.ctx)sound.ctx.suspend();}else if(sound.ctx)sound.ctx.resume();}
function toggleMute(){sound.mute(!sound.muted);$('mute').textContent='声音 '+(sound.muted?'关':'开');}
function toggleTouch(){const show=$('touch-toggle').checked;$('game').classList.toggle('touch',show);$('touch-controls').hidden=!show;resize();}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else{await document.documentElement.requestFullscreen();try{await screen.orientation.lock('landscape');}catch{}}}catch{toast('当前浏览器不支持全屏，仍可正常游玩。');}}
function resize(){const rotate=innerHeight>innerWidth&&mode!=='menu';input.rotated=rotate;input.clear();$('game').classList.toggle('rotated',rotate);const w=rotate?innerHeight:innerWidth,h=rotate?innerWidth:innerHeight;$('game').style.width=w+'px';$('game').style.height=h+'px';renderer.setSize(w,h,false);const half=17;camera.left=-half*w/h;camera.right=half*w/h;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix();}
$('start').onclick=reset;$('replay').onclick=reset;$('restart').onclick=reset;$('pause').onclick=()=>pause(true);$('resume').onclick=()=>pause(false);$('mute').onclick=toggleMute;$('touch-camera').onclick=()=>command('camera');$('fullscreen').onclick=$('pause-fullscreen').onclick=fullscreen;$('touch-toggle').onchange=toggleTouch;$('pause-touch').onclick=()=>{$('touch-toggle').checked=!$('touch-toggle').checked;toggleTouch();};$('pause-demo').onclick=()=>{invincible=!invincible;usedDemo ||= invincible;$('pause-demo').textContent='演示无敌：'+(invincible?'开':'关');};$('quality').onchange=()=>{const high=$('quality').value==='high';renderer.setPixelRatio(Math.min(devicePixelRatio,high?1.6:1));renderer.shadowMap.enabled=high;resize();};addEventListener('resize',resize);document.addEventListener('fullscreenchange',()=>{input.clear();resize();});
function blocked(x,z,r=.88){if(x<-17.9||x>17.9||z>12||z<-216)return true;if(z<-65.8&&z>-82.2&&(x<-13.2||x>-6.8))return true;if(stage===2&&z>-175)return true;for(const b of [...world.colliders,...buildings.filter(b=>!b.dead)])if(Math.abs(x-b.x)<b.w/2+r&&Math.abs(z-b.z)<b.d/2+r)return true;return false;}
function burst(x,z,color=0xffb555,n=16,y=1){for(let i=0;i<n;i++){if(sparks.length>=195)sparks.shift();sparks.push({x,y,z,vx:(Math.random()-.5)*8,vy:2+Math.random()*6,vz:(Math.random()-.5)*8,life:.3+Math.random()*.5,total:.8,color,scale:.08+Math.random()*.24});}}
function ring(x,z,radius,color='red',life=.5){const m=new T.Mesh(ringGeo,ringMats[color].clone());m.rotation.x=-Math.PI/2;m.position.set(x,.25,z);m.scale.setScalar(.1);m.userData.temporaryMaterial=true;scene.add(m);effects.push({mesh:m,life,total:life,radius});}
function explode(x,z,power,radius){burst(x,z,0xffb75c,23);ring(x,z,radius);sound.play('boom');hitShake=Math.max(hitShake,.1);for(const e of [...enemies,...buildings])if(!e.dead&&dist(e,{x,z})<radius+e.r*.45)damage(e,power);}
function damage(e,value){if(e.dead)return;e.hp-=value;e.flash=.08;if(e.hpMesh)e.hpMesh.scale.x=Math.max(0,e.hp/e.maxHp);burst(e.x,e.z,0xffdf9b,3,1.4);if(e.hp>0)return;e.dead=true;e.root.visible=false;if(e.aimMesh)e.aimMesh.visible=false;score+=e.boss?2000:e.officer!==undefined?100:e.type==='soldier'?100:e.type==='cannon'?400:600;burst(e.x,e.z,e.officer!==undefined?0xbead83:0xf3b362,24);ring(e.x,e.z,e.boss?4:2.5);sound.play('boom');
 if(e.type!=='soldier'){const w=rubble(e.officer!==undefined);place(w,e.x,e.z);wrecks.push(w);}if(e.officer!==undefined){for(let i=0;i<e.count;i++){const p={id:prisoners.length,x:e.x+(i-(e.count-1)/2)*.9,z:e.z+3.5,officer:e.officer,state:'waiting',root:person(true,e.officer)};place(p.root,p.x,p.z);prisoners.push(p);}toast(e.officer?'军官已获救！靠近接上车，升级重武器。':'营房已打开！靠近队员即可接上车。');}
 if(e.boss){bossKilled++;bossTimer=2.8;toast('重型坦克已摧毁 · '+bossKilled+' / 4',2);if(bossKilled===4)win();}
}
function hurt(amount=1){if(player.dead||player.invuln>0||invincible||mode!=='playing')return;player.hp-=amount;player.invuln=1.15;hitShake=.4;sound.play('hit');burst(player.x,player.z,0xffd075,10);if(player.hp<=0){player.dead=2.2;deaths++;car.visible=false;$('death').hidden=false;for(const p of player.cargo){p.state='waiting';p.x=checkpoint.x+(Math.random()-.5)*3;p.z=checkpoint.z+2;place(p.root,p.x,p.z);p.root.visible=true;}player.cargo=[];player.level=Math.max(0,player.level-1);sound.play('boom');}hud();}
function fire(heavy=false){const cooldown=heavy?'heavyCD':'gunCD';if(player[cooldown]>0)return;player[cooldown]=heavy?.56:.105;let a=player.angle,target=null,best=999;for(const e of [...enemies,...buildings]){if(e.dead)continue;const d=dist(e,player);if(d>25||d<.3)continue;const da=Math.atan2(Math.sin(angle(e.x-player.x,e.z-player.z)-a),Math.cos(angle(e.x-player.x,e.z-player.z)-a));if(Math.abs(da)<.42&&d<best){best=d;target=e;}}if(target)a=angle(target.x-player.x,target.z-player.z);const grenade=heavy&&player.level===0,rocket=heavy&&!grenade;
 const m=new T.Mesh(bulletGeo,heavy?heavyMat:gold);m.scale.set(heavy?.2:.075,heavy?.2:.075,heavy?.65:.4);m.rotation.y=a;scene.add(m);const speed=heavy?(grenade?18:33):45;
 shots.push({mesh:m,x:player.x+Math.sin(a)*1.6,z:player.z-Math.cos(a)*1.6,px:player.x,pz:player.z,vx:Math.sin(a)*speed,vz:-Math.cos(a)*speed,life:heavy?(grenade?.7:1.2):.65,total:grenade?.7:1,enemy:false,heavy,grenade,damage:heavy?18:2,radius:heavy?(player.level>=2?4.3:2.9):0});sound.play(heavy?'heavy':'gun');burst(player.x+Math.sin(a)*1.7,player.z-Math.cos(a)*1.7,0xffd489,heavy?4:1,1.8);
}
function enemyShot(e,a,spread=0){const shotsCount=spread?3:1;for(let i=0;i<shotsCount;i++){const dir=a+(i-(shotsCount-1)/2)*spread,speed=e.boss?10:e.type==='soldier'?9:11;const m=new T.Mesh(bulletGeo,red);m.scale.setScalar(e.type==='soldier'?.16:.26);scene.add(m);shots.push({mesh:m,x:e.x+Math.sin(dir)*(e.r+.2),z:e.z-Math.cos(dir)*(e.r+.2),vx:Math.sin(dir)*speed,vz:-Math.cos(dir)*speed,life:3.5,enemy:true,heavy:false,damage:1});}sound.tone(90,.12,'triangle',.13,45);}
function mortar(x,z){const mesh=new T.Mesh(ringGeo,ringMats.red.clone());mesh.rotation.x=-Math.PI/2;mesh.position.set(x,.26,z);scene.add(mesh);hazards.push({x,z,life:1.5,total:1.5,mesh});}
function updateEnemies(dt){for(const e of enemies){if(e.dead)continue;const d=dist(e,player);e.root.visible=Math.abs(e.z-player.z)<42;if(d>31||player.dead){e.aimMesh.visible=false;continue;}if(e.boss){e.phase+=dt;const targetX=Math.sin(e.phase*.43+bossSpawned)*11;e.x+=clamp(targetX-e.x,-dt*2.5,dt*2.5);e.root.position.x=e.x;}else if(e.type==='soldier'&&d<16&&d>5){const vx=(player.x-e.x)/d*dt*.85,vz=(player.z-e.z)/d*dt*.85;if(!blocked(e.x+vx,e.z,.35))e.x+=vx;if(!blocked(e.x,e.z+vz,.35))e.z+=vz;e.root.position.set(e.x,Math.sin(time*9+e.x)*.035,e.z);}
 if(e.wind>0){e.wind-=dt;e.aimMesh.visible=true;e.aimMesh.position.set(e.x+Math.sin(e.aim)*10,.22,e.z-Math.cos(e.aim)*10);e.aimMesh.rotation.z=-e.aim; // Local plane rotates around its normal after lying flat.
 e.aimMesh.rotation.set(-Math.PI/2,0,-e.aim);
 if(e.wind<=0){e.aimMesh.visible=false;enemyShot(e,e.aim,e.boss?.2:0);if(e.boss&&bossSpawned>=3)mortar(player.x,player.z);e.cool=e.boss?1.7:e.type==='soldier'?2.9:2.5;}}
 else{e.cool-=dt;if(e.cool<=0&&d<25){e.aim=angle(player.x-e.x,player.z-e.z);e.wind=e.boss?.85:e.type==='soldier'?.5:.75;}}
 const a=angle(player.x-e.x,player.z-e.z);if(e.root.userData.turret)e.root.userData.turret.rotation.y=e.wind>0?e.aim:a;else e.root.rotation.y=a;
 if(d<e.r+.65){if(e.type==='soldier'){damage(e,9);score+=25;}else hurt(1);}}
}
function updateShots(dt){for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.life-=dt;s.px=s.x;s.pz=s.z;s.x+=s.vx*dt;s.z+=s.vz*dt;let remove=s.life<=0;s.mesh.position.set(s.x,s.grenade?1+Math.sin((1-s.life/s.total)*Math.PI)*3:1.35,s.z);
 if(s.enemy){if(!player.dead&&segmentDistance(player.x,player.z,s.px,s.pz,s.x,s.z)<1.0){hurt(s.damage);remove=true;}if(buildings.some(b=>!b.dead&&Math.abs(s.x-b.x)<2.5&&Math.abs(s.z-b.z)<2.2))remove=true;}
 else{for(const e of [...enemies,...buildings]){if(e.dead)continue;if(segmentDistance(e.x,e.z,s.px,s.pz,s.x,s.z)<e.r){if(!s.heavy)damage(e,s.damage);remove=true;break;}}if(s.heavy&&remove)explode(s.x,s.z,s.damage,s.radius);}
 if(remove){s.mesh.removeFromParent();shots.splice(i,1);}}
}
function segmentDistance(x,z,ax,az,bx,bz){const dx=bx-ax,dz=bz-az,t=clamp(((x-ax)*dx+(z-az)*dz)/(dx*dx+dz*dz||1),0,1);return Math.hypot(x-ax-t*dx,z-az-t*dz);}
function updateRescue(dt){for(const p of prisoners){if(p.state!=='waiting')continue;const d=dist(p,player);p.root.visible=Math.abs(p.z-player.z)<37;p.root.position.y=Math.abs(Math.sin(time*4+p.id))*.06;if(d<5&&d>1.7&&player.cargo.length<8&&!player.dead){const nx=p.x+(player.x-p.x)/d*dt*3,nz=p.z+(player.z-p.z)/d*dt*3;if(!blocked(nx,nz,.3)){p.x=nx;p.z=nz;p.root.position.x=nx;p.root.position.z=nz;p.root.rotation.y=angle(player.x-p.x,player.z-p.z);}}
 if(d<2.2&&player.cargo.length<8&&!player.dead){p.state='aboard';p.root.visible=false;player.cargo.push(p);score+=150;sound.play('rescue');if(p.officer){player.level=Math.min(2,player.level+1);sound.play('upgrade');toast(player.level===1?'军官加入！K 已升级为远程导弹。':'重武器升级！导弹爆炸范围扩大。');}else toast('队员上车 · '+player.cargo.length+' / 8',1.8);}}
 const onPad=Math.hypot(player.x-7,player.z+145)<5.8;
 if(onPad&&player.cargo.length&&!player.dead){extract+=dt;extractCount+=dt;if(extractCount>.5){extractCount=0;const p=player.cargo.shift();p.state='rescued';rescued++;score+=500;sound.play('rescue');player.hp=Math.min(5,player.hp+1);toast('队员安全撤离 · '+rescued+' / 9',2);}heliDepart=0;}
 else extract=extractCount=0;
 if(rescued>0&&!player.cargo.length&&onPad){if(heliDepart===0)heliDepart=.001;checkpoint={x:0,z:-156};if(player.level===0)player.level=1;}
 if(heliDepart>0)heliDepart+=dt;chopper.position.set(7,5+Math.sin(time*2)*.2+(heliDepart>1?Math.min(18,(heliDepart-1)*3):0),-145-(heliDepart>1?Math.min(30,(heliDepart-1)*5):0));chopper.userData.rotor.rotation.y=time*32;chopper.visible=Math.abs(player.z+145)<50&&heliDepart<7;heliring.material.opacity=.4+Math.sin(time*3)*.18;
}
function zone(){if(stage===2)return 4;if(player.z<-132)return 3;if(player.z<-89)return 2;if(player.z<-55)return 1;return 0;}
const zones=[['01 / 林地前线','炸开营房，营救军官'],['02 / 河桥炮阵','从左侧桥梁渡河'],['03 / 战俘营区','炸开两座营房，接回队员'],['04 / 直升机接应','在绿色停机坪停留，送队员撤离'],['05 / 装甲封锁','击破四辆重型坦克']];
function updateProgress(dt){maxProgress=Math.max(maxProgress,clamp(-player.z/205,0,1));const z=zone();if(z!==lastZone){lastZone=z;toast(zones[z][1],3);if(z===2)checkpoint={x:-10,z:-87};if(z===3)checkpoint={x:0,z:-135};}
 if(player.z<-177&&stage<2){stage=2;checkpoint={x:0,z:-178};bossTimer=.9;toast('装甲封锁！红线锁定后及时变向，击破四辆重型坦克。',5);}
 if(stage===2&&bossKilled<4&&!enemies.some(e=>e.boss&&!e.dead)){bossTimer-=dt;if(bossTimer<=0){bossSpawned++;addEnemy('tank',bossSpawned%2?-9:9,-199,bossSpawned>0);toast('重型坦克 '+bossSpawned+' / 4 · 注意炮击预警',2.5);}}
 let target;if(stage===2)target=enemies.find(e=>e.boss&&!e.dead);else if(player.z>-55){target=buildings.find(b=>!b.dead&&b.officer)||{x:-10,z:-63};}else if(player.z>-83)target={x:-10,z:-79};else if(player.z>-130){target=buildings.find(b=>!b.dead&&b.z<-90)||{x:7,z:-145};}else if(player.cargo.length&&player.z>-169)target={x:7,z:-145};else target={x:0,z:-185};
 if(target){const a=angle(target.x-player.x,target.z-player.z);pointer.visible=dist(target,player)>7&&!player.dead;pointer.position.set(player.x+Math.sin(a)*3.9,.3,player.z-Math.cos(a)*3.9);pointer.rotation.set(-Math.PI/2,0,-a);}else pointer.visible=false;
}
function win(){mode='win';sound.play('win');input.clear();$('result').hidden=false;$('boss').hidden=true;const secs=Math.round(elapsed),rank=usedDemo?'演示':rescued===9&&deaths===0?'S':rescued>=6?'A':rescued>=3?'B':'C';$('result-stats').innerHTML=`<div><span>营救评级</span><strong>${rank}</strong></div><div><span>安全撤离</span><strong>${rescued}/9</strong></div><div><span>行动得分</span><strong>${score}</strong></div><div><span>耗时 / 增援</span><strong>${Math.floor(secs/60)}:${String(secs%60).padStart(2,'0')} / ${deaths}</strong></div>`;
 let best=0;try{best=Number(localStorage.getItem('jackal3d.v1.best')||0);if(!usedDemo&&score>best){best=score;localStorage.setItem('jackal3d.v1.best',String(best));}}catch{}$('record').textContent=usedDemo?'本局开启过演示无敌，不计入最高分。':`个人最高分 ${best} · 再挑战：全部 9 人撤离、零次增援。`;$('replay').focus();}
function hud(){for(let i=0;i<5;i++){let e=$('health').children[i];if(!e){e=document.createElement('i');$('health').appendChild(e);}e.className=i<player.hp?'':'lost';}$('protection').textContent=invincible?'演示无敌已开启':player.invuln>0?'增援保护中':'';$('cargo').textContent=player.cargo.length+' / 8';$('rescued').textContent=rescued+' / 9';$('score').textContent=String(score).padStart(6,'0');$('weapon').textContent=['K 榴弹 · 初始型','K 导弹 · 一级强化','K 导弹 · 范围强化'][player.level];$('lives').textContent='无限增援 · 已复活 '+deaths+' 次';const z=zone();$('sector').textContent=zones[z][0];$('objective').textContent=zones[z][1];$('progress').style.width=Math.round(maxProgress*100)+'%';const boss=enemies.find(e=>e.boss&&!e.dead);$('boss').hidden=!boss||mode==='win';if(boss){$('boss-title').textContent='重型坦克 '+bossSpawned+' / 4';$('boss-health').style.width=(boss.hp/boss.maxHp*100)+'%';}}
function update(dt){elapsed+=dt;player.invuln=Math.max(0,player.invuln-dt);player.gunCD-=dt;player.heavyCD-=dt;
 if(player.dead>0){player.dead-=dt;if(player.dead<=0){Object.assign(player,{x:checkpoint.x,z:checkpoint.z,hp:5,invuln:3.2,angle:0,dead:0});car.visible=true;$('death').hidden=true;for(const s of shots)s.life=0;toast('增援抵达 · 3 秒保护，继续行动');}}
 else{const a=input.get();const speed=a.boost?12:8.3;let dx=a.x*speed*dt,dz=a.y*speed*dt; // Both camera presets have the same horizontal right/forward axes.
 if(Math.hypot(dx,dz)>.0001){player.angle=angle(dx,dz);if(!blocked(player.x+dx,player.z))player.x+=dx;if(!blocked(player.x,player.z+dz))player.z+=dz;if(Math.random()<dt*18)burst(player.x,player.z,0xc5b487,1,.18);car.userData.wheels.forEach(w=>w.rotation.x+=speed*dt*1.8);}if(a.fire)fire();if(a.heavy)fire(true);
 car.position.set(player.x,Math.sin(time*22)*.018*(Math.abs(a.x)+Math.abs(a.y)),player.z);car.rotation.y=player.angle;car.rotation.z=clamp(-a.x*.045,-.06,.06);}
 shield.visible=!player.dead&&(player.invuln>0||invincible);shield.position.set(player.x,.15,player.z);shield.scale.setScalar(1+Math.sin(time*8)*.03);car.visible=!player.dead;
 updateEnemies(dt);updateShots(dt);updateRescue(dt);updateProgress(dt);
 for(let i=hazards.length-1;i>=0;i--){const h=hazards[i];h.life-=dt;h.mesh.scale.setScalar(2.8*(1-h.life/h.total));h.mesh.material.opacity=.4+Math.sin(time*20)*.3;if(h.life<=0){burst(h.x,h.z,0xffae56,26);ring(h.x,h.z,3);sound.play('boom');if(dist(h,player)<3)hurt();h.mesh.removeFromParent();h.mesh.material.dispose();hazards.splice(i,1);}}
 sound.update(elapsed);hudTimer-=dt;if(hudTimer<=0){hudTimer=.1;hud();}}
function visuals(dt){for(let i=sparks.length-1;i>=0;i--){const p=sparks[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vy-=15*dt;if(p.life<=0)sparks.splice(i,1);}for(let i=0;i<sparks.length;i++){const p=sparks[i];dummy.position.set(p.x,Math.max(.1,p.y),p.z);dummy.scale.setScalar(p.scale*Math.min(1,p.life*3));dummy.rotation.set(p.life*5,p.life*3,0);dummy.updateMatrix();sparkMesh.setMatrixAt(i,dummy.matrix);sparkMesh.setColorAt(i,new T.Color(p.color));}sparkMesh.count=sparks.length;sparkMesh.instanceMatrix.needsUpdate=true;if(sparkMesh.instanceColor)sparkMesh.instanceColor.needsUpdate=true; for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;const t=1-e.life/e.total;e.mesh.scale.setScalar(e.radius*(.3+t));e.mesh.material.opacity=(1-t)*.7;if(e.life<=0){disposeTransient(e.mesh);effects.splice(i,1);}}
 if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('visible');}hitShake=Math.max(0,hitShake-dt);}
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.04);last=now;const active=mode==='playing';if(active||mode==='menu'||mode==='win')time+=dt;if(active)update(dt);if(active||mode==='win')visuals(dt);
 if(mode!=='menu')car.scale.setScalar(1);let tx=mode==='menu'?-2:player.x*.33,tz=mode==='menu'?-10:player.z-6;if(mode==='menu'){car.visible=true;car.position.set(5,0,-7);car.rotation.y=-.45;car.scale.setScalar(1.5);chopper.visible=false;pointer.visible=shield.visible=false;}const offset=view?[0,44,2]:[0,33,27];camera.position.set(tx+offset[0]+(Math.random()-.5)*hitShake,offset[1],tz+offset[2]);camera.lookAt(tx,0,tz);sun.position.set(tx-18,35,tz+12);sun.target.position.set(tx,0,tz);
 for(const chunk of world.chunks){const b=chunk.mesh.geometry.boundingBox;chunk.mesh.visible=b.max.z>tz-65&&b.min.z<tz+45;}renderer.render(scene,camera);}
toggleTouch();resize();$('start').disabled=false;$('start').textContent='开始行动 · Enter';requestAnimationFrame(frame);
