const {setup,out}=require('./inspect.cjs');const assert=require('node:assert/strict');const fs=require('node:fs'),path=require('node:path');
(async()=>{const {browser,context,page,errors}=await setup({width:1280,height:720});const checks=[];const ok=(name,details)=>{checks.push({name,result:'pass',details});console.log('PASS',name);};
try{
 await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>!!document.fullscreenElement),false);ok('Enter starts without requesting fullscreen');
 for(let camera=0;camera<2;camera++){if(camera)await page.keyboard.press('KeyC');const p=await page.evaluate(()=>({...__qa.player,cargo:[]}));await page.keyboard.down('KeyW');await page.waitForTimeout(300);await page.keyboard.up('KeyW');const q=await page.evaluate(()=>({x:__qa.player.x,z:__qa.player.z}));assert(q.z<p.z-1);await page.keyboard.down('KeyD');await page.waitForTimeout(200);await page.keyboard.up('KeyD');await page.keyboard.down('KeyJ');await page.waitForTimeout(120);assert(await page.evaluate(()=>__qa.shots.some(s=>!s.enemy&&s.vx>40)));await page.keyboard.up('KeyJ');ok('Camera '+camera+' movement and firing use screen axes');}
 // Targeted diagnostics below edit state explicitly; separate from ordinary-input playthrough.
 for(let i=0;i<3;i++){await page.evaluate(()=>{__qa.player.invuln=0;__qa.hurt(5);});console.log('death-probe',await page.evaluate(()=>({state:__qa.state,dead:__qa.player.dead,hp:__qa.player.hp})));assert(await page.evaluate(()=>__qa.player.dead>0));await page.waitForTimeout(2400);assert(await page.evaluate(()=>__qa.player.hp===5&&__qa.player.invuln>0));}ok('Three consecutive deaths respawn with full armor and protection');
 await page.evaluate(()=>__qa.hurt(1));assert.equal(await page.evaluate(()=>__qa.player.hp),5);await page.waitForTimeout(3500);await page.evaluate(()=>__qa.hurt(1));assert.equal(await page.evaluate(()=>__qa.player.hp),4);ok('Respawn protection expires and normal damage resumes');
 await page.keyboard.press('Escape');await page.locator('#pause-demo').click();await page.keyboard.press('Enter');await page.evaluate(()=>{__qa.player.invuln=0;__qa.hurt(5);});assert.equal(await page.evaluate(()=>__qa.player.hp),4);await page.keyboard.press('Escape');await page.locator('#pause-demo').click();await page.keyboard.press('Enter');await page.evaluate(()=>__qa.hurt(1));assert.equal(await page.evaluate(()=>__qa.player.hp),3);ok('Explicit demo toggle enables and disables invulnerability');
 await page.keyboard.down('KeyW');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal(await page.evaluate(()=>__qa.state.mode),'paused');assert.equal(await page.evaluate(()=>__qa.input.keys.size),0);await page.keyboard.up('KeyW');await page.keyboard.press('Enter');ok('Focus loss pauses and clears held keys');
 await page.keyboard.press('KeyM');assert.equal(await page.evaluate(()=>__qa.sound.muted),true);await page.keyboard.press('KeyM');assert.equal(await page.evaluate(()=>__qa.sound.muted),false);ok('Sound toggles via keyboard');
 await page.evaluate(()=>{__qa.player.x=0;__qa.player.z=-64;});await page.keyboard.down('KeyW');await page.waitForTimeout(600);await page.keyboard.up('KeyW');assert(await page.evaluate(()=>__qa.player.z>-65.8));await page.evaluate(()=>{__qa.player.x=-10;__qa.player.z=-65;});await page.keyboard.down('KeyW');await page.waitForTimeout(1100);await page.keyboard.up('KeyW');assert(await page.evaluate(()=>__qa.player.z<-72));ok('River blocks vehicles outside the physical bridge');
 await page.keyboard.press('Escape');await page.locator('#restart').click();assert(await page.evaluate(()=>__qa.state.score===0&&__qa.state.deaths===0&&__qa.player.level===0&&__qa.prisoners.length===0));ok('Restart resets combat, rescue, upgrade and scoring state');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'functional.json'),JSON.stringify({method:'real keyboard plus explicitly marked targeted state setup',checks,errors},null,2));
}finally{await browser.close();}
 // Touch verification uses Chromium touch events with two simultaneous contacts.
for(const viewport of [{width:844,height:390},{width:390,height:844}]){const {browser,context,page,errors}=await setup(viewport,true);try{await page.locator('#touch-toggle').check();await page.screenshot({path:path.join(out,`phone-${viewport.width}-menu.png`)});await page.locator('#start').click();await page.waitForTimeout(500);const rotated=viewport.height>viewport.width;assert.equal(await page.locator('#game').evaluate(e=>e.classList.contains('rotated')),rotated);assert.equal(await page.evaluate(()=>!!document.fullscreenElement),false);
const stick=await page.locator('#stick').boundingBox(),fire=await page.locator('[data-action="fire"]').boundingBox();const cx=stick.x+stick.width/2,cy=stick.y+stick.height/2;const client=await context.newCDPSession(page);const p=await page.evaluate(()=>({x:__qa.player.x,z:__qa.player.z}));
await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx,y:cy,id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx+(rotated?36:0),y:cy+(rotated?0:-36),id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx+(rotated?36:0),y:cy+(rotated?0:-36),id:1},{x:fire.x+fire.width/2,y:fire.y+fire.height/2,id:2}]});await page.waitForTimeout(1800);
assert(await page.evaluate(p=>__qa.player.z<p.z-8,p));assert(await page.evaluate(()=>__qa.input.get().fire));await page.locator('#touch-camera').dispatchEvent('click');assert(await page.evaluate(()=>__qa.input.get().fire&&Math.abs(__qa.input.axis.y)>.5));await page.locator('#touch-camera').dispatchEvent('click');await page.screenshot({path:path.join(out,`phone-${viewport.width}-multitouch.png`)});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await page.evaluate(()=>!__qa.input.get().fire&&__qa.input.axis.x===0&&__qa.input.axis.y===0));
await page.locator('#touch-camera').click();assert.equal(await page.evaluate(()=>__qa.state.view),1);await page.locator('#pause').click();assert.equal(await page.evaluate(()=>__qa.state.mode),'paused');await page.evaluate(()=>{document.documentElement.requestFullscreen=()=>Promise.reject(new Error('QA fullscreen rejection'));});await page.locator('#pause-fullscreen').click();await page.locator('#resume').click();assert.equal(await page.evaluate(()=>__qa.state.mode),'playing');await page.waitForTimeout(500);await page.screenshot({path:path.join(out,`phone-${viewport.width}-fallback.png`)});assert.deepEqual(errors,[]);
ok('Touch '+viewport.width+'x'+viewport.height+' multitouch, inverse rotation, release, camera, pause and fullscreen fallback');const video=page.video();await context.close();await video.saveAs(path.join(out,`phone-${viewport.width}.webm`));await video.delete();}finally{await browser.close();}}
fs.writeFileSync(path.join(out,'functional.json'),JSON.stringify({method:'desktop keyboard; targeted state edits for regression; CDP touch viewport simulation, not a physical phone',checks,errors},null,2));
})().catch(e=>{console.error(e);process.exit(1);});
