const {setup,out}=require('./inspect.cjs');const fs=require('node:fs'),path=require('node:path');
(async()=>{const {browser,context,page,errors}=await setup({width:1280,height:720},true);const log=[];let held=new Set();
const setKeys=async keys=>{const next=new Set(keys);for(const k of held)if(!next.has(k))await page.keyboard.up(k);for(const k of next)if(!held.has(k))await page.keyboard.down(k);held=next;};
const state=()=>page.evaluate(()=>({p:{x:__qa.player.x,z:__qa.player.z,dead:__qa.player.dead,cargo:__qa.player.cargo.length,level:__qa.player.level,hp:__qa.player.hp},...__qa.state,b:__qa.buildings.map(b=>({x:b.x,z:b.z,dead:b.dead})),boss:__qa.enemies.filter(e=>e.boss&&!e.dead).map(e=>({x:e.x,z:e.z,hp:e.hp})),waiting:__qa.prisoners.filter(p=>p.state==='waiting').map(p=>({x:p.x,z:p.z}))}));
async function move(x,z,tol=.6){const start=Date.now();while(Date.now()-start<24000){const s=await state();if(s.p.dead){await setKeys([]);await page.waitForTimeout(500);continue;}const dx=x-s.p.x,dz=z-s.p.z;if(Math.hypot(dx,dz)<tol){await setKeys(['KeyJ','KeyK']);return;}const keys=['KeyJ','KeyK'];if(dx>tol*.6)keys.push('KeyD');if(dx<-tol*.6)keys.push('KeyA');if(dz>tol*.6)keys.push('KeyS');if(dz<-tol*.6)keys.push('KeyW');await setKeys(keys);await page.waitForTimeout(90);}throw new Error('Navigation stalled at '+JSON.stringify(await state())+' target '+[x,z]);}
async function aim(x,z){const s=await state(),a=Math.atan2(x-s.p.x,-(z-s.p.z)),oct=Math.round(a/(Math.PI/4));const map={0:['KeyW'],1:['KeyW','KeyD'],2:['KeyD'],3:['KeyS','KeyD'],4:['KeyS'],'-4':['KeyS'],'-3':['KeyS','KeyA'],'-2':['KeyA'],'-1':['KeyW','KeyA']};await setKeys(['KeyJ','KeyK',...map[oct]]);await page.waitForTimeout(50);await setKeys(['KeyJ','KeyK']);}
async function capture(name){await page.screenshot({path:path.join(out,name+'.png')});log.push({name,...await state()});console.log(name,JSON.stringify((await state()).p));}
try{await page.keyboard.press('Enter');await page.waitForTimeout(600);
 // Recording follows ordinary keyboard inputs, with no teleports, damage edits or invincibility.
 await page.evaluate(()=>{const q=__qa;q.audioParts=[];q.recorder=new MediaRecorder(q.sound.capture.stream,{mimeType:'audio/webm'});q.recorder.ondataavailable=e=>q.audioParts.push(e.data);q.recorder.start();});
 await move(10,-8);await aim(10,-16);await page.waitForTimeout(1300);await move(10,-12);await page.waitForTimeout(700);await capture('officer-upgrade');
 await move(0,-21);await move(0,-37);await move(-11,-37);await aim(-11,-44);await page.waitForTimeout(1100);await move(-11,-40);await page.waitForTimeout(1300);await capture('first-rescue');
 await move(0,-48);await move(0,-54);await move(-10,-54);await move(-10,-63);await capture('river-bridge');await move(-10,-87);await move(-10,-94);await move(-10,-103);await aim(-10,-110);await page.waitForTimeout(1400);await move(-10,-106);await page.waitForTimeout(1300);await capture('prison-camp');
 await move(0,-107);await move(0,-138);await move(7,-144);await setKeys([]);await page.waitForTimeout(5200);await capture('helicopter-evacuation');
 await move(6,-126);await move(11,-123);await aim(11,-117);await page.waitForTimeout(1300);await move(11,-114);await page.waitForTimeout(1100);await move(7,-144);await setKeys([]);await page.waitForTimeout(1800);
 await move(0,-155);await move(0,-179);await capture('boss-arena');
 const start=Date.now();let captured=0;while(Date.now()-start<160000){const s=await state();if(s.mode==='win')break;if(s.p.dead){await setKeys([]);await page.waitForTimeout(500);continue;}const b=s.boss[0];if(b){if(Math.hypot(b.x-s.p.x,b.z-s.p.z)>18)await move(s.p.x,-184,1);await aim(b.x,b.z);await page.waitForTimeout(240);if(s.bossSpawned!==captured){captured=s.bossSpawned;await capture('tank-wave-'+captured);}}else await page.waitForTimeout(250);}
 await setKeys([]);const final=await state();await capture('result');if(final.mode!=='win')throw new Error('No victory: '+JSON.stringify(final));
 const audio=await page.evaluate(()=>new Promise(resolve=>{__qa.recorder.onstop=async()=>{const b=new Blob(__qa.audioParts,{type:'audio/webm'});const a=new Uint8Array(await b.arrayBuffer());let str='';for(let i=0;i<a.length;i+=8192)str+=String.fromCharCode(...a.subarray(i,i+8192));resolve(btoa(str));};__qa.recorder.stop();}));fs.writeFileSync(path.join(out,'playthrough-audio.webm'),Buffer.from(audio,'base64'));
 fs.writeFileSync(path.join(out,'playthrough.json'),JSON.stringify({result:'pass',capture_mode:'realtime-automation',input:'ordinary keyboard, no game-state edits',errors,log,final},null,2));console.log('COMPLETE',JSON.stringify(final));
 }catch(e){console.error(e);await page.screenshot({path:path.join(out,'playthrough-error.png')});fs.writeFileSync(path.join(out,'playthrough-error.json'),JSON.stringify({error:String(e),errors,log,state:await state()},null,2));process.exitCode=1;}finally{const video=page.video();await context.close();await video.saveAs(path.join(out,'playthrough.webm'));await video.delete();await browser.close();}
})();
